# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
project 'UserProfileFirebaseEX.xcodeproj'

target 'UserProfileFirebaseEX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserProfileFirebaseEX
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  target 'UserProfileFirebaseEXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UserProfileFirebaseEXUITests' do
    # Pods for testing
  end

end
