# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ProfileFirebaseX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProfileFirebaseX
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  
  target 'ProfileFirebaseXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProfileFirebaseXUITests' do
    # Pods for testing
  end

end
